site_name: Pythonパッケージの作り方
site_url: https://daizutabi.github.io/takuhai/
repo_url: https://github.com/daizutabi/takuhai/
edit_uri: ''

theme:
  name: readthedocs
  language: 'jp'
docs_dir: sources
site_dir: docs

extra:
  search:
    language: 'jp'

markdown_extensions:
  - admonition

google_analytics:
  - 'UA-110929554-1'
  - 'auto'

pages:
  - Home: index.md
  - Python実行環境: environment.md
  - プロジェクトの作成: project.md
  - PyPIへのアップロード: pypi.md
  - ローカルでのテスト: local-test.md
  - CIでのテスト: ci-test.md
  - Anacondaへのアップロード: anaconda.md
  - ビルドとデプロイの自動化: ci-deploy.md
